### ISSUE TITLE
Missing commits?

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/yii2-bootstrap4#10]
It looks like there are commits missing from yii/bootstrap. For example: https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/NavBar.php#L114 should not be there anymore (see https://github.com/yiisoft/yii2-bootstrap/blob/master/src/NavBar.php#L114). This is a commit from Commits on Jun 13, 2016. Is there a reason for such a step back?

It looks like at least 4 years back in time :grinning:

**Comment by tomlutzenberger** [comment]
This is a separate project with different code, which was built up on the old one to save time. Means, old commits are not relevant to understand the current code.

**Comment by Thoulah** [comment]
Could you please reply in a way that is actually relevant to the reported issue?

**Comment by tomlutzenberger** [comment]
It seems there was a misunderstanding. I'm sorry about that.
To me, it sounded like "Commits from the old project are missing" (which are irrelevant to the current code base)

Can you take a look at the links you posted? It looks like the line numbers changed since you wrote it.

**Comment by Thoulah** [comment]
For example, the issue solved here: https://github.com/yiisoft/yii2-bootstrap/issues/137 was reintroduced with this step back. Why was yii2-bootstrap4 based on an older version of yii2-bootstrap?
