### ISSUE TITLE
Bootstrap 4.3.0

### ISSUE THREAD

**Issue by mihan007** [yiisoft/yii2-bootstrap4#105]
According to https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/ new version of bootstrap available. Do this project possible to use with it out of box or some changes required?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-bootstrap4/blob/master/composer.json#L40  here constraint should be `~4.2|~4.3`.

**Comment by machour** [comment]
Does it really make sense to keep these stricts constraints ?

**Comment by rob006** [comment]
> https://github.com/yiisoft/yii2-bootstrap4/blob/master/composer.json#L40 here constraint should be `~4.2|~4.3`.

It does not matter - `~` allows to increase last digit, so `~4.2` matches also `4.3` and `4.4`. If we want to change it, it makes more sense to use `^4.2` so it will be more obvious how it works.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-bootstrap4/commit/2fbcb1ead65015d6cb101d3766204937f35487ed

**Comment by mihan007** [comment]
hm. @samdark you sticked bootstrap version to 4.2 but the issue about upgrading to 4.3. why did you close it?

**Comment by rob006** [comment]
@mihan007 it is not sticked, see https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by mihan007** [comment]
Got it, thanks
