### ISSUE TITLE
Bootstrap4 Tab Widget not working

### ISSUE THREAD

**Issue by asmythe** [yiisoft/yii2-bootstrap4#108]
### What steps will reproduce the problem?
Add a BS4 tab widget to a page.
Click on the tabs ... nothing happens

### What's expected?
Tab label html content should not show up
When you click on a tab, you should see the content for that tab

### What do you get instead?
Tab label html shows up as code
tab border appears when you hover, but when you click, nothing happens

### Additional info
<img width="696" alt="screen shot 2019-02-19 at 8 42 02 am" src="https://user-images.githubusercontent.com/3144947/53019282-6506fd00-3422-11e9-882c-0cc19744ae0d.png">

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.16
| PHP version      | 7.1.23
| Operating system | macOS 10.14.3
| jQuery | 3.3.1

**Comment by machour** [comment]
For HTML in labels, this is the intended behavior. You need to set `encodeLabels` to `true` to allow HTML.

For the tab selection, could you show how you called the widget?

**Comment by asmythe** [comment]
I set encodeLabels to true and I still see the HTML. Here's my code:

```
<?= yii\bootstrap4\Tabs::widget([
    'encodeLabels' => true,
//    'itemOptions' => ['class'=>'tab-pane fade in'],
    'items' => [
        [
            'options' => ['id' => 'sponsors'],
            'label' => "Sponsors",
            'content' => "<div>Sponsors Tab content</div>",
            'active' => true,
        ],
        [
            'options' => ['id' => 'participants'],
            'label' => 'Participants <span class="tt">12</span>',
            'content' => "<div>Participants Tab content</div>",
            'active' => false,
        ],
        [
            'options' => ['id' => 'attendees'],
            'label' => "Attendees",
            'content' => "<div>Attendees Tab content</div>",
            'active' => false,
        ],
        [
            'options' => ['id' => 'resources'],
            'label' => "Resources",
            'content' => "<div>Resources Tab content</div>",
            'active' => false,
        ],
    ],
]);

```

**Comment by asmythe** [comment]
Here's a link to my test page

[http://qa.teamforte.info/site/tab-test](http://qa.teamforte.info/site/tab-test)

**Comment by machour** [comment]
Sorry, I meant `false` not `true` for labels.

Can you try removing all `active` settings from your tab? Yii will make the first one active by default.

**Comment by asmythe** [comment]
doesn't matter ... whether I set it false or true, I see the HTML. I removed all the active settings. Still no good.

**Comment by machour** [comment]
Confirmed:

* `encodeLabels` globally doesn't do much
* There's a problem with the generated code when specifying the id in `options`.

Here's a workaround for your case while we work on a fix:

```
<?= yii\bootstrap4\Tabs::widget([
    'items' => [
        [
            'label' => "Sponsors",
            'content' => "<div>Sponsors Tab content</div>",
        ],
        [
            'label' => 'Participants <span class="tt">12</span>',
            'encode' => false,
            'content' => "<div>Participants Tab content</div>",
        ],
        [
            'label' => "Attendees",
            'content' => "<div>Attendees Tab content</div>",
        ],
        [
            'label' => "Resources",
            'content' => "<div>Resources Tab content</div>",
        ],
    ],
]);
```

**Comment by asmythe** [comment]
Thank you for the workaround. I will definitely use it. It doesn't fix the label encoding problem, but the tabs work. I really appreciate your help on this.

**Comment by machour** [comment]
With `encode => false` on the second item, the label isn't encoded anymore for me:
![screen shot 2019-02-19 at 5 00 03 pm](https://user-images.githubusercontent.com/304450/53028813-e2089580-3467-11e9-8f8a-f6350ea2eabc.png)

Isn't that the case for you? 🤔

**Comment by asmythe** [comment]
I still have the problem

```
<?= yii\bootstrap4\Tabs::widget([
	'encodeLabels' => false,
    'items' => [
        [
            'label' => "Sponsors",
            'content' => "<div>Sponsors Tab content</div>",
        ],
        [
            'label' => 'Participants <span class="tt">12</span>',
            'content' => "<div>Participants Tab content</div>",
        ],
        [
            'label' => "Attendees",
            'content' => "<div>Attendees Tab content</div>",
        ],
        [
            'label' => "Resources",
            'content' => "<div>Resources Tab content</div>",
        ],
    ],
]);
?>

```
<img width="1738" alt="screen shot 2019-02-19 at 11 25 51 am" src="https://user-images.githubusercontent.com/3144947/53030642-37797e00-3439-11e9-8564-58835c3a4d2b.png">

**Comment by asmythe** [comment]
... but if I set it at the item level, it does work, e.g.

```
        [
            'label' => 'Participants <span class="tt">12</span>',
            'encode' => false,
            'content' => "<div>Participants Tab content</div>",
        ],

```
works.

But setting encldoeLabels = false does not work.

**Comment by machour** [comment]
@simialbi do you think you can have a look at the id problems ? Not sure how to fix the conflict, knowing that Nav also treats the ids from `options`.

Basically: 

```php
echo yii\bootstrap4\Tabs::widget([
    'items' => [
        [
            'options' => ['id' => 'pane1'],
            'label' => 'Tab 1',
            'content' => '<div>Content 1</div>',
        ],
        [
            'label' => 'Tab 2',
            'content' => '<div>Content 2</div>',
        ],
    ],
]);
```

Produces HTML with a duplicate `id`
```html
<ul id="w0" class="nav nav-tabs">
  <li id="pane1" class="nav-item active"> <!-- first occurence -->
    <a class="nav-link active" href="#pane1" data-toggle="tab" role="tab" aria-controls="pane1" aria-selected="true">Tab 1</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#w0-tab1" data-toggle="tab" role="tab" aria-controls="w0-tab1" aria-selected="false">Tab 2</a>
  </li>
</ul>
<div class="tab-content">
  <div id="pane1" class="tab-pane active">  <!-- second occurence -->
    <div>Content 1</div>
  </div>
  <div id="w0-tab1" class="tab-pane">
    <div>Content 2</div>
  </div>
</div>




```

**Comment by simialbi** [comment]
@machour I'll have a look

**Comment by simialbi** [comment]
@machour  #110 fixes this wrong behaviour
