### ISSUE TITLE
"nav" class is always added to Nav element

### ISSUE THREAD

**Issue by pappfer** [yiisoft/yii2-bootstrap4#114]
Even if I add a custom class to my `Nav` element, the "nav" class is always added, which can cause certain problems.

This code:
```php
Nav::widget([
    'options' => ['class' => 'navbar-nav mr-auto'],
    'items' => [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'Folder', 'url' => ['/folder/index']],
        ...
    ],
]);
```

will generate this HTML:
```html
<ul id="w1" class="navbar-nav mr-auto nav">...</ul>
```

I can see that the `nav` class is always added here: https://github.com/yiisoft/yii2-bootstrap4/blob/c86f47924aff618524eaa7e0a9bffe346df007f7/src/Nav.php#L119
If the `Nav` element is inside a `Navbar` element then it will make some padding issues. Removing the `nav` class would solve the issue.

**Comment by simialbi** [comment]
Just do:
```php
Nav::widget([
    'options' => ['class' => ['widget' => '', 'navbar-nav', 'mr-auto']],
    'items' => [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'Folder', 'url' => ['/folder/index']],
        ...
    ],
]);
```
should prevent adding nav class

**Comment by pappfer** [comment]
@simialbi Yes, it works this way indeed, thank you.
