### ISSUE TITLE
Pagination BS4

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2-bootstrap4#120]
Hi,
I am not sure if I missed something, but is pagination for BS4 supported .. ?
Seems that Yii2 [LinkPager](https://www.yiiframework.com/doc/guide/2.0/en/output-pagination) generates different markup than [BS4](https://getbootstrap.com/docs/4.0/components/pagination/).
Or can be default LinkPager configured also for BS4 .. ?
Thank you.

EDIT:

I figured out, that minor modification is needed (classes `page-item` and `page-link` must be properly applied), following seems to work with default LinkPager:

```
use yii\widgets\LinkPager;

$pagination = new Pagination();
$param = $pagination->pageParam;
$page = $_REQUEST[$param] ?? 0;
$page = max(0, (intval($page)-1));

$html = LinkPager::widget([
	'pagination' => new yii\data\Pagination(),
	'options' => ['class' => 'pagination justify-content-center'],
	'pageCssClass' => 'page-item',
	'prevPageCssClass' => $page == 0 ? 'page-link' : '',
	'nextPageCssClass' => $page == 0 ? 'page-item' : 'page-link',
	'linkOptions' => ['class' => 'page-link'],
])
```

**Comment by ricpelo** [comment]
What about coding a `yii\bootstrap4\LinkPager` that hides all the above ad-hoc code?

**Comment by Thoulah** [comment]
As already suggested in #98 :)

**Comment by machour** [comment]
@ricpelo could you provide a PR for this?

**Comment by ricpelo** [comment]
> @ricpelo could you provide a PR for this?

I'd love to do it, but unfortunately I'm busy now with another higher priority issues :cry:
