### ISSUE TITLE
yii2-bootstrap4 Progress

### ISSUE THREAD

**Issue by 4meck** [yiisoft/yii2-bootstrap4#121]
when installed [locale] =>ru_RU and $percent = 80;
the code 
> Html::addCssStyle($options, ['width' => Yii::$app->formatter->asPercent($percent / 100)], true);

sets the value with a space before the % sign
> style="width: 80 %;"

### What steps will reproduce the problem?
https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Progress.php#L152

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.17
| PHP version      | 7.2
| Operating system | Win10

**Comment by machour** [comment]
Yes, we probably want simple math here instead of formatting, feel free to open a PR for this.
