### ISSUE TITLE
contentOptions in Tabs not working

### ISSUE THREAD

**Issue by mostADont** [yiisoft/yii2-bootstrap4#125]
contentOptions in Tabs not working.
this param not used in Tabs.

**Comment by simialbi** [comment]
There is no `$contentOptions` property in class `Tabs`. Do you have some example what you exactly mean?

**Comment by mostADont** [comment]
In the documentation:

>      * - items: array, optional, can be used instead of `content` to specify a dropdown items
>      *   configuration array. Each item can hold three extra keys, besides the above ones:
>      *     * active: bool, optional, whether the item tab header and pane should be visible or not.
>      *     * content: string, required if `items` is not set. The content (HTML) of the tab pane.
>      *     * contentOptions: optional, array, the HTML attributes of the tab content container.

I wanted to add a class to the panel

**Comment by simialbi** [comment]
You're right. But that part of documentation is some artifact from the upgrade from [yiisoft/yii2-bootstrap](https://github.com/yiisoft/yii2-bootstrap).

I think it will be removed.
If I understand you correctly, you want to add options here (between the asterisks **):
```html
<ul id="w0" class="nav nav-tabs">
    <li class="nav-item active"><a class="nav-link active" href="#pane1" data-toggle="tab" role="tab" aria-controls="pane1" aria-selected="true">Tab 1</a></li>
    <li class="nav-item"><a class="nav-link" href="#w0-tab1" data-toggle="tab" role="tab" aria-controls="w0-tab1" aria-selected="false">Tab 2</a></li>
</ul>
<div class="tab-content">
    <div id="pane1" class="tab-pane active" **my-attribute="my-value"**>
        <div>Content 1</div>
    </div>
    <div id="w0-tab1" class="tab-pane">
        <div>Content 2</div>
    </div>
</div>
```
If that's your plan you can use `options` instead of `contentOptions` like this:
```php
Tabs::widget([
	'items' => [
		[
			'options' => ['id' => 'pane1', **'my-attribute' => 'my-value'],**
			'label' => 'Tab 1',
			'content' => '<div>Content 1</div>',
		],
		[
			'label' => 'Tab 2',
			'content' => '<div>Content 2</div>',
		],
	],
]);
```
