### ISSUE TITLE
.invalid-feedback error message does not shown

### ISSUE THREAD

**Issue by BloodyAltair** [yiisoft/yii2-bootstrap4#126]
### What steps will reproduce the problem?
- Create ActiveForm field of type `widget (\yii\jui\DatePicker::class)`
- Submit the form with invalid date field

### What's expected?
Normal error message display. `is-invalid` class for input element

### What do you get instead?
Error message does not shown
![изображение](https://user-images.githubusercontent.com/22257078/56074435-30c51280-5dbb-11e9-8b09-fd4d178b7028.png)

### Additional info
This problem may appear on other ActiveField types, i've not tested it yet

| Q                | A
| ---------------- | ---
| Yii vesion       | ~2.0.14
| PHP version      | PHP 7.2.15 (cli) (built: Feb  9 2019 02:46:46) ( NTS )
| Operating system | Linux (Arch as host, Debian as docker guest)

**Comment by machour** [comment]
Hi

Could you check the conversation in #122 ?

**Comment by simialbi** [comment]
I think this is a Problem of `yii\jui\DatePicker` who may not be compatible with bs4. An alternative that works is https://github.com/kartik-v/yii2-widget-datepicker

**Comment by BloodyAltair** [comment]
@simialbi Yep. I've tested it with built-in ActiveField s and a couple of plugins. It is a problem of `yii\jui\DatePicker`. I'll close this issue and submit an issue to DatePicker repo.
Thanks.
