### ISSUE TITLE
Missed the constant of the extra large modal.

### ISSUE THREAD

**Issue by shoomlix** [yiisoft/yii2-bootstrap4#129]
### What steps will reproduce the problem?
Open the class yii\bootstrap4\Modal
### What's expected?
To find the constant of the extra large modal.
### What do you get instead?
That is missing.

**Comment by samdark** [comment]
Feel free to do a pull request adding it.

**Comment by shoomlix** [comment]
> Feel free to do a pull request adding it.
Ok, thank you)

**Comment by shoomlix** [comment]
> Feel free to do a pull request adding it.

Ok, thank you)

**Comment by shoomlix** [comment]
@samdark, I did it.
