### ISSUE TITLE
Nav-bar item activate doesn't work in Dropdown

### ISSUE THREAD

**Issue by AsDonAs** [yiisoft/yii2-bootstrap4#133]
### What steps will reproduce the problem?

Open the class yii\bootstrap4\Dropdown

### What's expected?

Using $itemOptions for activate link/item in Nav-bar (and for over options).

### What do you get instead?

$itemOptions not used and in result - we can't activate menu-item.

**Comment by simialbi** [comment]
@AsDonAs : Could you please post some **code** example how you used the widget and what you expected

**Comment by AsDonAs** [comment]
Not me: yii\bootstrap4\Nav using this option for activating menu-items in dropdown menu-item.

Behavior that i expecting: when i use yii\bootstrap4\Nav i can see activate sub-item if main-item is dropdown, like  i use yii\bootstrap\Nav. Difference in generating items for dropdowns. In bootstrap4 version we haven't main html-element, who taking options for items.

Check [this](https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Dropdown.php#L47).

Dropdown items have "options". One of this options - it's "active" for item, used in Nav-widget.

And like in old-version - this options taking from params, but doesn't use now, check [this](https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Dropdown.php#L112).

For check this - you can make menu like:
```
echo Nav::widget([
        'options' => ['class' => ['widget' => 'navbar-nav']],
        'items' => [
            ['label' => 'Main', 'url' => ['/site/index']],
            [
                'label' => 'Admin',
                'items' => [
                    ['label' => 'Users', 'url' => ['/site/users']],
                    ['label' => 'Roles', 'url' => ['/site/roles']],
                    ['label' => 'Statuses', 'url' => ['/site/statuses']],
                ],
            ],
        ],
]);
```

When you on /site/users page - this menu sub-item doesn't active.
This problems missing in old version, because template for generating Dropdown-items another.

**Comment by Thoulah** [comment]
Can you check this again after https://github.com/yiisoft/yii2-bootstrap4/commit/c2fadd4effc19520a1d930a67e6af233450f7687 please? I didn't realize this issue existed.

**Comment by AsDonAs** [comment]
Checked 2.0.3 version, still have problem.

In old (bootstrap 3) template we have this item, for taking $itemOptions.
![yii-bootstrap4-issue133](https://user-images.githubusercontent.com/24962746/58689446-b747aa80-838f-11e9-8e1a-f708d65f1292.jpg)

In (bootstrap 4 2.0.3) template we have this generations:
![yii-bootstrap4-issue133-2](https://user-images.githubusercontent.com/24962746/58689465-c0387c00-838f-11e9-8780-b129f0210a67.jpg)
1. For items not being dropdowns we haven't "div" with options, because have [false-check](https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Dropdown.php#L132). For change it we can try move "div" generating, [here](https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Dropdown.php#L123).
2. This time, when we generating "div", we getting "active" class, but we haven't css-rule about "activate" this "div" element. Users can set their selectors, but this ain't base in widget, and this must be documented. Another way, add unique class for this item and css-rule for class.

**Comment by Thoulah** [comment]
I'm not 100% sure the fix was ready.

**Comment by Thoulah** [comment]
Right now it seems to work for `Dropdown`, but not for `Nav` somehow

**Comment by Thoulah** [comment]
We have a working solution. We're currently checking the code and the tests to make sure it's all fine, but it should all be ready soon.
