### ISSUE TITLE
Parent li should not contain active class

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/yii2-bootstrap4#135]
From the Tabs widget, `<li class="nav-item active">` should not contain the `active` class. See [Tabs](https://getbootstrap.com/docs/4.3/components/navs/#tabs).

**Comment by simialbi** [comment]
There is a problem. Tabs are using the `Nav` component. The `Nav` component in combination with `Navbar` has to activate the `<li>`, without combination with `Navbar` the `<a>`. So the most simple (and 100% compatible) solution was to activate both. See navbar:
https://getbootstrap.com/docs/4.3/components/navbar/#supported-content

**Comment by Thoulah** [comment]
Would an `activateParent` in `Nav` (defaults to true) be helpful? This could be set to false from `Tabs`.
