### ISSUE TITLE
Unable to install via Composer

### ISSUE THREAD

**Issue by ilbassa** [yiisoft/yii2-bootstrap4#142]
### What steps will reproduce the problem?
`composer require yiisoft/yii2-bootstrap4`
### What's expected?
Installation of yii2-boostrap4 in "vendor" folder
### What do you get instead?
`Installation failed, reverting ./composer.json to its original content.

  [InvalidArgumentException]
  Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.`

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2
| PHP version      |5.6.30
| Operating system |Debian 9

**Comment by samdark** [comment]
There's no `npm-signature` anywhere in this project. Are you sure nothing global in your project interferes?

**Comment by ilbassa** [comment]
If I run  `composer update` it update all the packages.
Then if I run `composer require yiisoft/yii2-bootstrap4` I have the npm-signature exception.
What can interfere if the composer update run well?

**Comment by samdark** [comment]
Looks like you're still using fxp plugin and an old one: https://stackoverflow.com/questions/49940646/composer-fail-on-update-with-npm-signature-error

But it's better to upgrade to https://asset-packagist.org/. See https://github.com/yiisoft/yii2-app-basic as reference.

**Comment by ilbassa** [comment]
Hi, I have removed `fxp/composer-asset-plugin` from `composer.lock` then I have launched
```$ composer require yiisoft/yii2-bootstrap4
Using version ^2.0 for yiisoft/yii2-bootstrap4
./composer.json has been updated
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information                                  Package operations: 3 installs, 0 updates, 0 removals
  - Installing fxp/composer-asset-plugin (v1.1.4): Loading from cache
  - Installing npm-asset/bootstrap (4.3.1): Downloading (100%)
  - Installing yiisoft/yii2-bootstrap4 (2.0.2): Downloading (100%)
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Writing lock file
Generating autoload files
```
So I have successfully installed `yii2-boostrap4` but it have installed `fxp/composer-asset-plugin (v1.1.4`) maybe this can cause problem in future updates?

**Comment by simialbi** [comment]
If you add
```json
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
    "config": {
      "fxp-asset": {
            "enabled": false
        }
    }
```
to your `composer.json`, you'll not use `fxp/composer-asset-plugin` any more. Instead you'll use `https://asset-packagist.org`, which is much more efficient. I think the install problems will disappear too.
