### ISSUE TITLE
Make sure document have ready before call script

### ISSUE THREAD

**Issue by hscstudio** [yiisoft/yii2-bootstrap4#147]
For safety, we should make sure document have ready before call script that refer to elemen HTML 

We can use ``` jQuery(document).ready```

Change https://github.com/yiisoft/yii2-bootstrap4/blob/996cdb01e257d19685ca8e105a27bf7c6cf6953c/src/BootstrapWidgetTrait.php#L78

```
$js = "jQuery('#$id').$name($options);";
```

to 

```
$js = "jQuery(document).ready(function() { jQuery('#$id').$name($options); })";
```

**Comment by Thoulah** [comment]
Next line is `$view->registerJs($js);`.
See https://www.yiiframework.com/doc/api/2.0/yii-web-view#registerJs()-detail
`public void registerJs ( $js, $position = self::POS_READY, $key = null )`

> POS_READY: enclosed within jQuery(document).ready(). This is the default value. Note that by using this position, the method will automatically register the jQuery js file.

**Comment by hscstudio** [comment]
> self::POS_READY

Should change to this on line 79?

```
$view->registerJs($js, \yii\web\View::POS_READY);
```

**Comment by hscstudio** [comment]
I have tried it but it result error

```
jquery.min.js:2 Uncaught TypeError: jQuery(...).modal is not a function
    at HTMLDocument.<anonymous> ((index):147)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
```

**Comment by Thoulah** [comment]
> > self::POS_READY
> 
> Should change to this on line 79?
> 
> ```
> $view->registerJs($js, \yii\web\View::POS_READY);
> ```

No, because View::POS_READY is already the default.

**Comment by hscstudio** [comment]
> > > self::POS_READY
> > 
> > 
> > Should change to this on line 79?
> > ```
> > $view->registerJs($js, \yii\web\View::POS_READY);
> > ```
> 
> No, because View::POS_READY is already the default.

May this is bug, because if we view source on browser, it generate this

```
jQuery(function ($) {
   jQuery('#myModal').modal({"show":false});
})
```

Fyi, I place modal declaration on layout main

```
Modal::begin([
    'id' => 'myModal',
    'headerOptions' => ['id' => 'modalHeader'],
    'footerOptions' => ['id' => 'modalFooter'],
    'footer' => ''
]);
echo "<div id='modalContent'></div>";
Modal::end();
```

**Comment by Thoulah** [comment]
Please have a read: https://stackoverflow.com/a/6454701

>These function all do the same things - execute some code when DOM is ready. `$(document).ready(function(){})` is the original one, and it matches the underlying javascript API.

> "$" and "jQuery" which accept function as an arguments were created as shortcuts to avoid repeating such a common construct. Accepting a function which accepts $ as its first argument is a further syntax sugar - now you get convenience of the closures without the need to do it yourself.

I also tried your code (in a view file, not layout) without errors.
