### ISSUE TITLE
error message not displayed

### ISSUE THREAD

**Issue by mtvldc** [yiisoft/yii2-bootstrap4#163]
Hello,
In \yii\bootstrap4\ActiveField, if I need an input group and I use inputTemplate, like:

```php
<?php echo $form->field($model, 'demo', [
'inputTemplate' => '<div class="input-group"><div class="input-group-prepend">
<span class="input-group-text">@</span>
</div>{input}</div>',
]); ?>
```

Then the error message is not displayed, if the input fails validation. The div with class "invalid-feedback" has a CSS rule display:none. This rule should be deactivated, but it's not.

Can you fix this? Thank you!

**Comment by Thoulah** [comment]
In what way are you validating? Server-side and/or client side?
Please share model as well.

**Comment by mtvldc** [comment]
I am validating server side and client side.
In the model I have this rule for validating the 'net_area' attribute:

```
public function rules() {
    return [
        // .....
        ['net_area', 'required', 'message' => 'Vă rugăm să completați câmpul «{attribute}».'],
        [
            'net_area',
            'number',
            'min' => 0,
            'max' => 20000,
            'message' => 'Vă rugăm să introduceți un număr cu cel mult două zecimale.',
            'tooSmall' => 'Numărul introdus trebuie să fie mai mare sau egal cu {min}.',
            'tooBig' => 'Numărul introdus trebuie să fie mai mic sau egal cu {max}.',
            'numberPattern' => '/^\s*[-+]?[0-9]*\.?[0-9]{1,2}([eE][-+]?[0-9]+)?\s*$/'
        ],
        // .....
    ];
}
```
In the view file, _form.php, I have this:
```
<div class="col-6 col-lg-5">
    <?=
    $form->field($apartment, 'net_area', [
        'template' => 
        '{label}
        <div class="input-group">
            {input}
            <div class="input-group-append">
                <span class="input-group-text">mp</span>
            </div>
        </div>
        {hint}
        {error}'
    ])->input('number', ['step' => '0.01'])
    ?>
</div>
```
The {input} is inside a div with class "input-group". When I have simple inputs, everything is fine. When the input is inside a div with class "input-group", the error message is not displayed, if the input fails validation.

I want to add text to the right side of the input, like this: https://getbootstrap.com/docs/4.0/components/input-group/

Thank you!

**Comment by mtvldc** [comment]
My problem is the same as this one: #36

**Comment by Thoulah** [comment]
I have tried both your examples and it works client side in both cases. I didn't bother server-side validation for now.

```
$model = new \yii\base\DynamicModel([
    'demo1',
    'demo2',
]);
$model->addRule(['demo1', 'demo2'], 'required');

$form = \yii\bootstrap4\ActiveForm::begin();
    echo $form->field($model, 'demo1', [
        'inputTemplate' => '<div class="input-group"><div class="input-group-prepend">
        <span class="input-group-text">@</span>
        </div>{input}</div>',
    ]);
    
    echo $form->field($model, 'demo2', [
        'template' => 
        '{label}
        <div class="input-group">
            {input}
            <div class="input-group-append">
                <span class="input-group-text">mp</span>
            </div>
        </div>
        {hint}
        {error}'
    ])->input('number', ['step' => '0.01']);

    echo Html::submitButton('Submit', ['class' => 'btn btn-primary']);
\yii\bootstrap4\ActiveForm::end();
```

![image](https://user-images.githubusercontent.com/21957118/62200351-8121a980-b385-11e9-940b-b4cbf062a46c.png)

**Comment by mtvldc** [comment]
The output is:
```
npm-asset/bootstrap      4.3.1 
yiisoft/yii2-bootstrap4  2.0.6   The Twitter Bootstrap extension for the Yii framework
```
I noticed that on getbootstrap.com ([https://getbootstrap.com/docs/4.3/components/forms/#validation](url)) the code for input validation looks like this:
```
<div class="input-group">
    <div class="input-group-prepend">
        <span class="input-group-text" id="inputGroupPrepend">@</span>
    </div>
    <input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required="">
    <div class="invalid-feedback">
        Please choose a username.
    </div>
</div>
```
The div.invalid-feedback is a child of div.input-group.

The code generated by class yii\bootstrap4\ActiveField looks like this:
```
<div class="input-group">
    <input type="number" id="t001apartment-net_area" class="form-control is-invalid" name="T001Apartment[net_area]" step="0.01" aria-required="true" aria-invalid="true">
    <div class="input-group-append">
        <span class="input-group-text">mp</span>
    </div>
</div>
<small class="form-text text-muted">Suprafața utilă cuprinde: camera de zi, ...</small>
<div class="invalid-feedback">Vă rugăm să completați câmpul «Suprafața utilă».</div>
```
The div.invalid-feedback is a sibling of div.input-group.

When div.invalid-feedback is a child of div.input-group everything works fine. Thank you!

**Comment by Slayvin** [comment]
When I use radioList or checkBoxList, the error message is not displayed.
This is because of what's explained above : the template generated is incorrect and the _div.invalid-feedback_ is not a sibling of the input(s) anymore.

**Comment by simialbi** [comment]
Yes you are right. As you can see on [bootstrap docs](https://getbootstrap.com/docs/4.3/components/forms/#supported-elements), there is some kind of inconsistency in the framework. It's the only situation with multiple inputs but only one feedback. Should be fixed now (see demo on http://demo.karlen.li/web/site/test).
