### ISSUE TITLE
Checkbox/radio with custom controls don't work for custom labels

### ISSUE THREAD

**Issue by flaviovs** [yiisoft/yii2-bootstrap4#169]
### What steps will reproduce the problem?

Create a form with checkbox/radio labels coming from a model's `getAttributeLabel()`:

```php
$form = \yii\bootstrap4\ActiveForm::begin();
$model = new \yii\base\DynamicModel([
    'bool' => true,
    'choice' => 1,
]);

echo $form->field($model, 'bool')
	  ->checkbox();

echo $form->field($model, 'choice')
	  ->radio();

ActiveForm::end();
```

Output:

![image](https://user-images.githubusercontent.com/1832699/63728605-214ddf80-c819-11e9-8f54-004647163555.png)

Now add custom labels:

```php
echo $form->field($model, 'bool')
	  ->label('My custom checkbox label')
	  ->checkbox();

echo $form->field($model, 'choice')
	  ->label('My custom radio label')
	  ->radio();
```

### What's expected?

Checkbox and radio button as above, but using the custom labels.

### What do you get instead?

![image](https://user-images.githubusercontent.com/1832699/63728657-4fcbba80-c819-11e9-931c-200a4873f775.png)

### Additional info

Custom control label is missing the `custom-control-label` class, and this might be causing this problem (side note: the `for` attribute is missing as well)

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.25
| Yii BS4       | 2.0.7
| PHP version      | 5.6
| Operating system | Debian + docker +  yiisoftware/yii2-php:5.6-apache image

**Comment by simialbi** [comment]
You're right. If you override the label the order of method calling changes changes. This causes that the `label tag` does not get the css class `custom-control-label`
Workaround:
```php
<?php
	$form  = \yii\bootstrap4\ActiveForm::begin();
	$model = new \yii\base\DynamicModel([
		'bool'   => true,
		'choice' => 1,
	]);

	echo $form->field($model, 'bool')
			  ->label('My custom checkbox label', ['class' => 'custom-control-label'])
			  ->checkbox();

	echo $form->field($model, 'choice')
			  ->label('My custom radio label', ['class' => 'custom-control-label'])
			  ->radio();

	\yii\bootstrap4\ActiveForm::end();
?>
```

**Comment by samdark** [comment]
That looks like a bug.

**Comment by simialbi** [comment]
I don't thinks it's a bug, it's more some kind of ***chicken and egg problem***. If you override the label with `->label()`, the label get's rendered before the input and at this point, the `label()` method does not know what kind of input will be rendered later. So when calling `checkbox()` or `radio()` the method knows that the label got overridden and do not render the label again. So it can add the needed label classes...

**Comment by samdark** [comment]
Do it make sense to have a label without `custom-control-label`?

**Comment by simialbi** [comment]
Yes, for each other `input` like `textInput`:
https://getbootstrap.com/docs/4.3/components/forms/#overview

**Comment by samdark** [comment]
Can't a call to `checkbox()` or `radio()` do the following?

```php
$labelOptions = ArrayHelper::remove($options, 'labelOptions', []);
Html::addCssClass($options, 'custom-control-label');
```

**Comment by simialbi** [comment]
The already do that at https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/ActiveField.php#L259. But that does not change anything in @flaviovs 2nd example. When the `checkbox()` change the label options, the label has already rendered:
```php
echo $form->field($model, 'bool') // 1. initialize class
	  ->label('My custom checkbox label') // 2. override label (get's already rendered)
	  ->checkbox(); // 3. render checkbox (label options are changed here too)
```

**Comment by samdark** [comment]
Ah, right :(

**Comment by samdark** [comment]
Seems we cannot solve it without major re-thinking of active form that is not going to happen in Yii 2.

**Comment by flaviovs** [comment]
Can't we override `->label()` in BS4's `ActiveField` and implement custom logic so that the custom control label class gets added for checkboxes/radios before calling `parent::label()`?

(Or maybe the overridden method could do all custom rendering by itself?)

I could try test a solution like this, but it would be good to know if it is feasible (or not) beforehand.

It is good that we have a workaround, but changing all `label()` calls in a huge system like I have here is not fun. If a fix is not possible we will have to stick to 2.0.4. :-(

**Comment by samdark** [comment]
Before calling `label()` we have no idea if we need the class.
