### ISSUE TITLE
NavBar - collapse

### ISSUE THREAD

**Issue by Dezyderyjczyk** [yiisoft/yii2-bootstrap4#175]
I installed the extension. I have js and css connected. I called these commands:

	NavBar::begin([
		'brandLabel' => Yii::$app->name,
		'brandUrl' => Yii::$app->homeUrl,
		'options' => [
			'id' => 'mainNav',
			'class' => 'bg-dark navbar-dark navbar-fixed-top',
		],
	]);
 echo Nav::widget([
		'options' => ['class' => 'navbar-nav navbar-right'],
		'items' => [
            ['label' => 'File', 'url' => ['/files'],],
            ...
			['label' => 'Login', 'url' => ['/site/login'],],
		]
	]);
NavBar::end();

And yet, all the time, regardless of the width, I have collapse

**Comment by simialbi** [comment]
You need to add the desired expand class (e.g. `navbar-expand-lg`):
https://getbootstrap.com/docs/4.3/components/navbar/#nav
