### ISSUE TITLE
Add support to override every class used

### ISSUE THREAD

**Issue by fabiomlferreira** [yiisoft/yii2-bootstrap4#189]
At the moment there are some widgets that we can't override all classes.
For example in Nav widget we have this

`if (empty($items)) {
            $items = '';
        } else {
            $linkOptions['data-toggle'] = 'dropdown';
            Html::addCssClass($options, ['widget' => 'dropdown']); // THIS IS OK WE CAN OVERRIDE
            Html::addCssClass($linkOptions, ['widget' => 'dropdown-toggle']); // THIS IS OK WE CAN OVERRIDE
            if (is_array($items)) {
                $items = $this->isChildActive($items, $active);
                $items = $this->renderDropdown($items, $item);
            }
        }

        Html::addCssClass($options, 'nav-item'); // THIS IS NOT OK WE CAN'T OVERRIDE
        Html::addCssClass($linkOptions, 'nav-link'); // THIS IS NOT OK WE CAN'T OVERRIDE

        if ($disabled) {
            ArrayHelper::setValue($linkOptions, 'tabindex', '-1');
            ArrayHelper::setValue($linkOptions, 'aria-disabled', 'true');
            Html::addCssClass($linkOptions, 'disabled'); 
        } elseif ($this->activateItems && $active) {
            Html::addCssClass($linkOptions, 'active'); 
        }`

This is an example of a problem that I'm facing at the moment, I think if we can override every class on the widgets this will became a lot more versatile.

**Comment by samdark** [comment]
Each widget adds an abstraction over a certain bootstrap component that is described using concrete set of classes and HTML tags. What's your use case for changing these?

**Comment by fabiomlferreira** [comment]
@samdark I was implementing a frontend template (bootstrap 4) that don't have the nav-link class, but since I can't override this that class was added automatically and use the css of the bootstrap.css. 
I fix it overriding the css but I think it's a good idea that we can override at least the nav-item and the nav-link. 

I undersant that this plugin is made for bootstrap 4 and in this case we should have that classes but sometimes the designer don't follow that and we don't have any way to override this behavior

**Comment by samdark** [comment]
That's controversial.

Anyway, how would you fix that? Would that require many changes?

**Comment by fabiomlferreira** [comment]
In this widget I think it's enough to change

```
 Html::addCssClass($options, 'nav-item'); 
 Html::addCssClass($linkOptions, 'nav-link');
```

to this

```
Html::addCssClass($options, ['widget' => 'nav-item']);
Html::addCssClass($options, ['widget' => 'nav-link']);
```
In this way we can override this classes easily. What you think?

**Comment by simialbi** [comment]
It's possible to do. But if we do, we should do this for all Widgets...
@smadark what do you think?

**Comment by samdark** [comment]
If that won't change defaults I'm fine with it.
