### ISSUE TITLE
Add Branch 2.1 jquery free.

### ISSUE THREAD

**Issue by cjtterabyte** [yiisoft/yii2-bootstrap4#20]
yii2.1 with bootstrap4 works well, we only have the problem of the different route of jquery in 2.0 and 2.1, seeing the roadmap of yii2.1 there are extensions that will be free of jquery, this is the time to do the same with bootstrap4 since You do not need jquery, as we are starting bootstrap4 it would be great to start with the new approaches.

https://github.com/yiisoft/yii2-bootstrap4/issues/17

**Comment by moplin** [comment]
Hey guys, I understand «half way» why we are trying to get rid of jquery. But I think if it should be better to have Jquery and js-bootstrap part as an opt in, some way to include it for those that will need it?
I am still trying to digest the "why" to take jquery out, but it is part of some clients requirements «they usually adapt really slow to change», and I have the feeling that jquery is not going anywhere soon. 
I do have more concerns regarding the use of bower that is being shut down.

**Comment by Thoulah** [comment]
They are only trying to get rid of jQuery from the core and official addons. Nothing will ever stop you from adding it with an asset or addon.

**Comment by mtangoo** [comment]
I was curiously following this. But then it is suddenly closed. @cjtterabyte  can you explain the closure?
I still think your case is valid. I haven't started using BS4 though, so I might be wrong...

**Comment by cjtterabyte** [comment]
@mtangoo Thanks for the follow-up close the issue, because there is already a branch yii 2.1-->yii 3.0, which is the branch 2.0 current, and the elimination of the jquery can be done from the assets.
