### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by ariefbayu** [yiisoft/yii2-bootstrap4#200]
Pardon if this already implemented. However, I search and see no mention in issues.

How should I implement [RTL](https://bootstrap.rtlcss.com/) within this library?

**Comment by bizley** [comment]
As I can see this is only a matter of replacing the CSS file with the RTL version (as stated in the linked guide) so you can do it with [customizing the asset](https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#customizing-asset-bundles) or [mapping it](https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#asset-mapping).
