### ISSUE TITLE
Failing to configure a label::after content in checkbox

### ISSUE THREAD

**Issue by denis-sanches** [yiisoft/yii2-bootstrap4#206]
### What steps will reproduce the problem?

1. Generate some form with Gii (CRUD Generator).
1. Use a ->checkbox() field.
1. Configure some CSS to append (::after) a red * for required fields' labels.

CSS:
```css
div.required label:after {
    content: " *";
    color: red;
    background-color: yellow; /* just for visual test */
}
```
views/usuario/_form.php (raw/example):
```php
<?php

use yii\bootstrap4\Html;
//use yii\widgets\ActiveForm;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Usuario */
/* @var $form yii\bootstrap4\ActiveForm */
?>

<div class="usuario-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ativo')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
```

### What's expected?

Append the red * after the label text for required fields as using the default `yii\widgets\ActiveForm` as follows:

![Captura de tela de 2021-01-15 11-13-48](https://user-images.githubusercontent.com/435461/104740140-574d7580-5726-11eb-85ab-f0dc80c034af.png)

### What do you get instead?

It's overlapping the dropbox, "appending" the label::after before the label, as follows (just changing the above PHP code to `use yii\bootstrap4\ActiveForm;` instead)

![Captura de tela de 2021-01-15 11-17-47](https://user-images.githubusercontent.com/435461/104740601-e65a8d80-5726-11eb-92b5-1f10846d6ef0.png)

### Additional info

It's my first time contributing here... and CSS is not my field.
I've tried some minimal changes to this getting working without having to pass a template option but with no success.
If that's not a bug and just a code configuration problem, my apologies in advance.
Ah... the same occurs with ->radio();

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.40 
| yii2-bootstrap4 | 2.0.9
| PHP version      |  7.4.3
| Operating system | Ubuntu 20.04

**Comment by simialbi** [comment]
It's because [custom controls](https://getbootstrap.com/docs/4.5/components/forms/#checkboxes) are used by default in `yii\bootstrap4\ActiveForm` and ::before and ::after are used to display the custom control.

**Comment by simialbi** [comment]
You can ovveride the template to use default checkboxes like this (untested)
```php
<?= $form->field($model, 'ativo', [
    'checkTemplate' => "{input}\n{label}\n{error}\n{hint}"
])->checkbox() ?>
```

**Comment by denis-sanches** [comment]
Hi, @simialbi. Thank you!!

I've tried overring the template but with no success.
In fact, this CSS seems to work to all cases in BS4, even radio():

```css
div.required > label::after, .custom-control::after {
    content: " *";
    color: red;
}
```

Again, thank you so much!
