### ISSUE TITLE
bootstrap pagination and disabled pjax

### ISSUE THREAD

**Issue by srakl** [yiisoft/yii2-bootstrap4#211]
I'm using Yii2 2.0.42.1. on my gridview i've changed to to POST and disabled pjax.

```
<?php Pjax::begin(['id'=>'id-pjax', 'timeout'=>false, 'enablePushState' => true, 'clientOptions' => ['type' => 'POST', 'url' => Url::to(['/test/default/dashboard'])]]); ?>

<?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'filterPosition' => \yii\grid\GridView::FILTER_POS_HEADER,
                'pager' =>[
                    'linkOptions'=> ['data-pjax' => '0'],
                    'class' => \yii\bootstrap4\LinkPager::class,
                ],
                ....
]); ?>

<?php Pjax::end(); ?>
```

when i add `'linkOptions'=> ['data-pjax' => '0'],` the pagination doesn't become bootstrap pagination, but the pagination works.

when i remove `'linkOptions'=> ['data-pjax' => '0'],` the pagition UI is bootstrap, but pagination doesn't work at all

any idea how to fix this? I also have multiple gridviews on the same page.

**Comment by bizley** [comment]
Thank you for your question.
In order for this issue tracker to be effective, it should only contain bug reports and feature requests.

We advise you to use our community driven resources:
* [The support forum](http://www.yiiframework.com/forum/)
* [The IRC chat room](http://www.yiiframework.com/chat/)
* [Slack](https://join.slack.com/t/yii/shared_invite/enQtMzQ4MDExMDcyNTk2LWUzN2RlZmJiMDdiZDIwOWI4M2U3ODYwOTRjZDk5MTY1ZWM3YTY5MTVkNzRiN2RlMWQxODA5N2ZmY2E5NWI2YTM)
* [The Definitive Guide to Yii](http://www.yiiframework.com/doc-2.0/guide-index.html)

If you are confident that there is a bug in the framework, feel free to provide information on how to reproduce it. This issue will be closed for now.
