### ISSUE TITLE
Bootstrap4 GridView Pager

### ISSUE THREAD

**Issue by mgabor411** [yiisoft/yii2-bootstrap4#215]
### What steps will reproduce the problem?
We developed a paginated site and above bootstrap4 doesn't work.

### What is the expected result?
In the Yii2 generated code doesn't included **"li" tag** class independent **class="page-item"** and **"a" tag** **class="page-link"**. 

### What do you get instead?
This is the bad one:
![image](https://user-images.githubusercontent.com/91549229/135106000-e7ba5166-dc8e-4a4e-93ed-e42869fb4d12.png)

I would like to see this one:
![image](https://user-images.githubusercontent.com/91549229/135106041-862c6447-b502-4122-a8a9-1fc5c12f8392.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4.9
| Operating system | Linux

**Comment by samdark** [comment]
Please post view template code where you initialize pagination.

**Comment by mgabor411** [comment]
> Please post view template code where you initialize pagination.

Dear samdark!

GridView initialize a pagination.

![image](https://user-images.githubusercontent.com/91549229/135148017-ec97be3b-7717-4392-9f0a-8c7a84cd1ae1.png)
### view - index.php

<?php Pjax::begin(); ?>
        <?= GridView::widget([
            'id' => 'grid-users',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => SerialColumn::class],
                [
                    'attribute' => 'username',
                    'headerOptions' => ['width' => '120px'],
                    'filter' => Html::activeInput('text', $searchModel, 'username', [
                        'class' => 'form-control',
                        'placeholder' => Module::t('app', '- text -'),
                        'autocomplete' => 'off',
                        'data' => [
                            'pjax' => true,
                        ],
                    ]),
                    'format' => 'raw',
                    'value' => function($model) {
                        $view = Yii::$app->controller->view;
                        return $view->render('_avatar_column', ['model' => $model]);
                    }
                ],
            ],
        ]); ?>
<?php Pjax::end(); ?>

**Comment by terabytesoftw** [comment]
> ### ¿Qué pasos reproducirán el problema?
> Desarrollamos un sitio paginado y por encima de bootstrap4 no funciona.
> 
> ### ¿Cuál es el resultado esperado?
> En el código generado por Yii2 no incluye **"li" tag** class independent **class="page-item"** y **"a" tag** **class="page-link".**
> 
> ### ¿Qué obtienes en su lugar?
> Este es el malo: ![image](https://user-images.githubusercontent.com/91549229/135106000-e7ba5166-dc8e-4a4e-93ed-e42869fb4d12.png)
> 
> Me gustaría ver este: ![image](https://user-images.githubusercontent.com/91549229/135106041-862c6447-b502-4122-a8a9-1fc5c12f8392.png)
> 
> ### Información adicional
> Q	UN
> Versión Yii	2.0.43
> Versión PHP	7.4.9
> Sistema operativo	Linux

If I have the code where, i can reproduce it with pleasure I will take a look .

**Comment by mgabor411** [comment]
> If I have the complete code where, i can reproduce it with pleasure I will take a look .

Has I understand, would you like to get a whole view file?

**Comment by mgabor411** [comment]
I think I catch the problem...

In the **yii\grid\GridView** class extends the **yii\widgets\BaseListView** class, around the line 256 the original framework use "base" **yii\widgets\LinkPager** class
![image](https://user-images.githubusercontent.com/91549229/135221606-8ba23c39-7e62-4b8e-8a5d-2f6d871cb28a.png)

When I change the LinkPager class to Bootstrap4 it works finally.
`$class = ArrayHelper::remove($pager, 'class', \yii\bootstrap4\LinkPager::className());`

![image](https://user-images.githubusercontent.com/91549229/135221931-23b2bfb7-a261-411e-a028-25c0723e5dc1.png)

Is there any solution in your mind for the feature? Because It's in the vendor section, what we use via dependency manager we don't want to change manually this line project-to-project.

**Comment by stekky81** [comment]
> I think I catch the problem...
> 
> In the **yii\grid\GridView** class extends the **yii\widgets\BaseListView** class, around the line 256 the original framework use "base" **yii\widgets\LinkPager** class ![image](https://user-images.githubusercontent.com/91549229/135221606-8ba23c39-7e62-4b8e-8a5d-2f6d871cb28a.png)
> 
> When I change the LinkPager class to Bootstrap4 it works finally. `$class = ArrayHelper::remove($pager, 'class', \yii\bootstrap4\LinkPager::className());`
> 
> ![image](https://user-images.githubusercontent.com/91549229/135221931-23b2bfb7-a261-411e-a028-25c0723e5dc1.png)
> 
> Is there any solution in your mind for the feature? Because It's in the vendor section, what we use via dependency manager we don't want to change manually this line project-to-project.

You can use DI container injection adding in your config file:

```
'container' => [
        'definitions' => [
                'yii\widgets\LinkPager' => 'yii\bootstrap4\LinkPager'
        ]
],
```
