### ISSUE TITLE
String nav item

### ISSUE THREAD

**Issue by xcopy** [yiisoft/yii2-bootstrap4#223]
### What steps will reproduce the problem?

I think string items should not be allowed OR should be transformed to nav link with the default URL (`#`)

https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Nav.php#L160

```php
echo yii\bootstrap4\Nav::widget([
    'items' => [
        'Item1', // string item
        [
            'label' => 'Item2',
            'url' => '/',
        ]
    ]
]);
```

### What's expected?

```html
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link" href="#">Item1</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/">Item2</a>
  </li>
</ul>
```

### What do you get instead?

```html
<ul class="nav">
  Item1
  <li class="nav-item">
    <a class="nav-link" href="/">Item2</a>
  </li>
</ul>
```

![image](https://user-images.githubusercontent.com/202339/177682517-f303df3c-2acc-4200-9f51-d14bf3f2e3a7.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.46-dev
| PHP version      | 8.0
| Operating system | Ubuntu 20.04

**Comment by bizley** [comment]
I disagree. We should not force developers to have link here if they don't want to.

**Comment by samdark** [comment]
I agree with @bizley forcing it isn't desirable.
