### ISSUE TITLE
Error when installing via composer

### ISSUE THREAD

**Issue by alejofonseca** [yiisoft/yii2-bootstrap4#23]
### What steps will reproduce the problem?
Running `composer require --prefer-dist yiisoft/yii2-bootstrap4`

### What's expected?
I was expecting Bootstrap 3 already installed to be updated to version 4

### What do you get instead?
Got this error: Could not find a version of package yiisoft/yii2-bootstrap4 matching your minimum-stability (stable)...

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.15.1
| PHP version      |7.2.5RC1
| Operating system |Windows 7 pro

**Comment by samdark** [comment]
Yes, the package has no stable version yet. It's expected.
