### ISSUE TITLE
NavBar collapse button alignment

### ISSUE THREAD

**Issue by smichae** [yiisoft/yii2-bootstrap4#25]
According to BS4 docs, "Navbar togglers are left-aligned by default, but should they follow a sibling element like a .navbar-brand, they’ll automatically be aligned to the far right. Reversing your markup will reverse the placement of the toggler."  (https://getbootstrap.com/docs/4.1/components/navbar/#toggler)

Should a new NavBar option be introduced to left or right align the toggler?

**Comment by paulobrandit** [comment]
thumbs up for @smichae for noticing this. can someone fixit? the navbar is not displaying properly because of this.

**Comment by simialbi** [comment]
I'm not sure an option is needed. To change alignment you can do this:
```php
NavBar::begin([
	'brandOptions' => [
		'class' => ['order-1']
	],
	'togglerOptions' => [
		'class' => ['order-0']
	]
]);
```

**Comment by Thoulah** [comment]
You are right, it it not needed. But it would make it simpler for people without the hassle of finding the correct classnames.

```
NavBar::begin([
	'brandOptions' => [
		'class' => ($this->navbarAlignRight) ? ['order-1'] : ['order-0'],
	],
	'togglerOptions' => [
		'class' => ($this->navbarAlignRight) ? ['order-0'] : ['order-1'],
	]
]);
```
(just an example)

**Comment by cjtterabyte** [comment]
For convenience you can create predefined classes:

```
navbarAlignRight = float-right
navbarAlignLeft = float-left
```

Or simply place the note in the documentation about the navbar and toggler alignment.
