### ISSUE TITLE
Update composer.json branch yii2 3.0.

### ISSUE THREAD

**Issue by cjtterabyte** [yiisoft/yii2-bootstrap4#27]
Yii vesion: 3.0.x-dev
PHP version: 7.1.17.
Operating system: Centos7.

Hi, please update composer.json:

it would be nice to update the composer.json to keep trying yii2-boostrap4 with yii2 branch 3.0.x-dev.

`
"require": {
    "yiisoft/yii2": "~2.0.15|~2.1.0|~3.0.0",
},
`

**Comment by dmirogin** [comment]
We did it at 2.2 branch
https://github.com/yiisoft/yii2-bootstrap/commit/d9ed9087d22a132bff51289083903d6453543151

**Comment by dmirogin** [comment]
Oookey, in this repo we have to do that
