### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by tumdav** [yiisoft/yii2-bootstrap4#34]
#### Package json example

```json
  "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-bootstrap4": "~1.0.0"
    },
```

#### Result
```
The requested package yiisoft/yii2-bootstrap4 ~1.0.0 is satisfiable by yiisoft/yii2-bootstrap4[1.0.x-dev] but these conflict with your requirements or minimum-stability.

```

| Q                | A
| ---------------- | ---
| Yii vesion       | latest |
| PHP version      | 5.4|
| Operating system | Mac OS|

**Comment by katarsies** [comment]
Package is not stable yet.
![image](https://user-images.githubusercontent.com/21752309/41768389-86f56e8a-7625-11e8-8fc1-d29a4587596f.png)

**Comment by tumdav** [comment]
@katarsies and how to use it ?

**Comment by schmunk42** [comment]
`composer require yiisoft/yii2-bootstrap4:dev-master`
