### ISSUE TITLE
The file or directory to be published does not exist: ROOTvendor/bower-asset/bootstrap/assets/js/vendor

### ISSUE THREAD

**Issue by tumdav** [yiisoft/yii2-bootstrap4#35]

**Comment by vedro-compota** [comment]
@tumdav If you use npm (like on so https://stackoverflow.com/questions/50028312/how-to-use-yii2-bootstrap4-extension-with-bootstrap-3-in-the-same-app) the problem may be in npm package structure, which is difference from bower package. This was reason in my case.

**Comment by simialbi** [comment]
This seems to be the problem: In the npm package of bootstrap the "popper.js" asset is not included. 
You may add `"npm-asset/popper.js": "~1.14"` to `composer.json` and override the source path like this (in web config):
```php
'assetManager' => [
	'bundles' => [
		'yii\bootstrap4\PopperAsset' => [
			'sourcePath' => '@npm/popper.js/package/dist'
		]
	]
]
```

**Comment by vedro-compota** [comment]
@simialbi thank you! Please tell how I got that version of popper should be "~1.14"? Where we can see it?

**Comment by simialbi** [comment]
Follow the instructions on [Asset packagist](https://asset-packagist.org/). It's a nice replacement of  fxp/composer-asset-plugin. There you can search for bower/npm packages and include with comoser. I got the path from downloaded zip [on this page](https://asset-packagist.org/package/detail?fullname=npm-asset/popper.js)

**Comment by vedro-compota** [comment]
>  I got the path from downloaded zip on popper.js' detail page

@simialbi thank you very much!

**Comment by snickom** [comment]
I made a pull request: https://github.com/yiisoft/yii2-bootstrap4/pull/40
