### ISSUE TITLE
Class yii\web\JqueryAsset not found

### ISSUE THREAD

**Issue by Driver86** [yiisoft/yii2-bootstrap4#41]
https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/BootstrapPluginAsset.php#L24
```
public $depends = [
     'yii\web\JqueryAsset',
```
But, https://github.com/yiisoft/yii2/blob/3.0/framework/UPGRADE.md
> Assets yii\web\JqueryAsset, yii\web\YiiAsset, yii\validators\ValidationAsset have been moved under yii\jquery\* namespace. Make sure you refer to the new full-qualified names of this classes.

Because of this, we get an error: Class yii\web\JqueryAsset not found...

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 3.0@dev
| PHP version      | any
| Operating system | any

**Comment by Thoulah** [comment]
Afaik master is not for 3.0. See https://github.com/yiisoft/yii2-bootstrap4/blob/2.0/src/BootstrapPluginAsset.php
