### ISSUE TITLE
Installing on yii2 advanced template

### ISSUE THREAD

**Issue by semir-karic** [yiisoft/yii2-bootstrap4#49]
Can this be used with yii2 advanced template.
I get the following errors while trying to do composer update

Problem 1
    - Conclusion: remove bower-asset/bootstrap v3.3.7
    - Conclusion: don't install bower-asset/bootstrap v4.1.3
    - Conclusion: don't install bower-asset/bootstrap v3.3.6
    - Conclusion: remove yiisoft/yii2-bootstrap 2.0.8|install bower-asset/bootstrap v3.3.6
    - Conclusion: don't install bower-asset/bootstrap v4.1.2
    - Conclusion: don't install bower-asset/bootstrap v3.3.7|install bower-asset/bootstrap v4.1.3|install bower-asset/bootstrap v4.1.2
    - Conclusion: don't install bower-asset/bootstrap v3.3.5
    - Conclusion: don't install bower-asset/bootstrap v4.1.1
    - Conclusion: don't install bower-asset/bootstrap v3.3.4
    - Installation request for yiisoft/yii2-gii ~2.0.0 -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - Installation request for yiisoft/yii2-bootstrap4 ~1.0.0@dev -> satisfiable by yiisoft/yii2-bootstrap4[1.0.x-dev].
    - yiisoft/yii2-debug 2.0.13 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.9 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.8 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.7 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.6 requires yiisoft/yii2-bootstrap * -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.5 requires yiisoft/yii2-bootstrap * -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.4 requires yiisoft/yii2-bootstrap * -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.3 requires yiisoft/yii2-bootstrap * -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.2 requires yiisoft/yii2-bootstrap * -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.13 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.12 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.11 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.10 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.1 requires yiisoft/yii2-bootstrap * -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-debug 2.0.0 requires yiisoft/yii2-bootstrap * -> satisfiable by yiisoft/yii2-bootstrap[2.0.8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - yiisoft/yii2-bootstrap 2.0.8 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.1 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.2 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.3 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.4 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.5 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.6 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.7 requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.3.7, v3.3.6, v3.3.5, v3.3.4, v3.3.2, v3.3.1, v3.3.0, v3.2.0, v3.1.1, v3.1.0].
    - yiisoft/yii2-bootstrap 2.0.0 requires bower-asset/bootstrap 3.2.* | 3.1.* -> satisfiable by bower-asset/bootstrap[v3.2.0, v3.1.1, v3.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.3.2, v4.0.0].
    - Can only install one of: bower-asset/bootstrap[v3.3.1, v4.0.0].
    - Can only install one of: bower-asset/bootstrap[v3.3.0, v4.0.0].
    - Can only install one of: bower-asset/bootstrap[v3.2.0, v4.0.0].
    - Can only install one of: bower-asset/bootstrap[v3.1.1, v4.0.0].
    - Can only install one of: bower-asset/bootstrap[v3.1.0, v4.0.0].
    - yiisoft/yii2-bootstrap4 1.0.x-dev requires bower-asset/bootstrap ~4.0 -> satisfiable by bower-asset/bootstrap[v4.1.3, v4.1.2, v4.1.1, v4.1.0, v4.0.0].
    - Conclusion: don't install bower-asset/bootstrap v4.1.0
    - Installation request for yiisoft/yii2-debug ~2.0.0 -> satisfiable by yiisoft/yii2-debug[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].

**Comment by simialbi** [comment]
Try if it works if you clear the `require-dev` section in your `composer.json`.
But if you do, you'll lose some debug functionality.

**Comment by semir-karic** [comment]
It works if you do that but then you lose all debug functionality like you
said.
Thanks anyway

**Comment by tecnoterabyte** [comment]
you can overwrite the asset:

```
'assetManager' => [
    'appendTimestamp' => true,
    'bundles' => [
        \yii\bootstrap\BootstrapAsset => [
            'sourcePath' => '@npm/bootstrap/dist',
	    'css' => [
	        'css/bootstrap.css',
            ],
        ],
    ],
]
```
it should work,

**Comment by p-Clerick** [comment]
I resolve this problem manually.
I try to install BOOTSTRAP4 on clear Yii-advansed app. All be Ok.
But migrate my StarterKit app to clear Advanced App was so difficulty. And I just save directory "/vendor/bower-asset/bootstrap" from Yii-advansed app to my StarterKit app.
And all works!
After this I manually plug GliphIcons to map Bootstarp4 app - like last recipe from here:
http://qaru.site/questions/59396/bootstrap-4-glyphicons-migration.

And now all works. 
I fix Bootstrap version in Composer from accidental update.

**Comment by bigrepository** [comment]
For those who didn't get it: Replacing BS3 with BS4 as described in the readme does not work for the yii2 advanced template, because

```
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0"
```

debug and gii both require BS3 through `"yiisoft/yii2-bootstrap": "~2.0.0"` and you are trying to uninstall BS3 and install BS4 ...therefore composer throws a "requirements could not be resolved"-error. 

You can try to circumvent this issue and add 

```
    "minimum-stability": "dev",
    "prefer-stable": true,
```

to your composer.json so composer - but be sure to check if you are using stable releases in a production environment!

**Comment by tomlutzenberger** [comment]
Please see my [comment](https://github.com/yiisoft/yii2-bootstrap4/issues/50#issuecomment-419743900) at issue #50

**Comment by machour** [comment]
This should be fixed now as both yii2-gii & yii2-debug were rewritten to be bootstrap independent.
Is there something to fix in the documentation?

**Comment by samdark** [comment]
No.
