### ISSUE TITLE
Installation problem - Can only install one of bootstrap v4 or v3.

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2-bootstrap4#50]
There is a problem with installation if you want to use a bootstrap v3.3.7 for other parts of app.
During composer installation I got an error and package was not installed.

### What steps will reproduce the problem?
Try to install package on project created based on advanced yii2 template.

### What's expected?
Make that package installed.

### What do you get instead?
```
G:\Web\root-users\studios>..\.tools\Composer\composer.bat require yiisoft/yii2-bootstrap4
Using version ^1.0@dev for yiisoft/yii2-bootstrap4
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yiisoft/yii2-bootstrap4 ^1.0@dev -> satisfiable by yiisoft/yii2-bootstrap4[1.0.x-dev].
    - Conclusion: remove bower-asset/bootstrap v3.3.7
    - Conclusion: don't install bower-asset/bootstrap v3.3.7
    - yiisoft/yii2-bootstrap4 1.0.x-dev requires bower-asset/bootstrap ^4.1.0 -> satisfiable by bower-asset/bootstrap[v4.1.3, v4.1.2, v4.1.1, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v4.1.3, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.1.2, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.1.1, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.1.0, v3.3.7].
    - Installation request for bower-asset/bootstrap (locked at v3.3.7) -> satisfiable by bower-asset/bootstrap[v3.3.7].
Installation failed, reverting ./composer.json to its original content.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.15.1
| PHP version      | 7.2
| Operating system | Windows 10 (CBB)

**Comment by tomlutzenberger** [comment]
As far as I know, you can't have 2 versions of the same package installed.
@raphael-fischer I just tested with a fresh clone of app-advanced. I removed `yii-debug` and `yii-gii` from `require-dev` as well as bootstrap from `require` *before* i ran `composer install`. Afterwards I had no problems installing bootstrap4.
Can you try to remove those packages and install bootstrap4?

**Comment by craiglondon** [comment]
@tomlutzenberger Your solution works, but then you loose GII and Debug.  =-/    Those packages will need to be updated to support BS4 as well.

**Comment by tomlutzenberger** [comment]
We're aware of that. But it takes time and some planing.

**Comment by marab** [comment]
Hi
Sorry but you mean  only advanced users that don't need Gii & Debug can use bootstrap 4.
Is there any date for changes?

**Comment by tesarm** [comment]
I was able to install yii-debug again after installing bootstrap4. 

I haven't tried yii-gii as I don't use it
