### ISSUE TITLE
No Auto Update Packagist.org

### ISSUE THREAD

**Issue by cjtterabyte** [yiisoft/yii2-bootstrap4#6]
Yii: 2.0.15.
PHP: 7.1

Hi packagist.org:

Current Update:

`e98188106e7fb1ce5efb13ec1e39449f34ef5385`

Cuurent Update Github:

`5b4861a8f53f8029675e812d096e9c9a8a60294f`

Thks,

**Comment by samdark** [comment]
Fixed.
