### ISSUE TITLE
Resetting widget counter has no effect

### ISSUE THREAD

**Issue by tomlutzenberger** [yiisoft/yii2-bootstrap4#60]
I'm currently trying to fix the tests and it seems that resetting the widget counter has no effect. Taking `ToggleButtonGroupTest` as example, neither `\yii\base\Widget::$counter = 0;` nor `ToggleButtonGroup::$counter = 0;` change the actual result of the test (see below).
The big problem is that even if I would test against an incremented counter ID, tests would break instantly if the order of the tests change.
Does someone of the core team have an idea why a public static property behaves like this?

### What steps will reproduce the problem?

Execute the tests and look for the ID's in `ToggleButtonGroupTest::testRadio` (second test in the class)

### What's expected?

Two inputs with the ID's `i1` and `i2`

### What do you get instead?

ID's `i3` and `i4`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | ~2.0
| PHP version      | 7.1
| Operating system | Win10x64

**Comment by samdark** [comment]
Where do you do it?

**Comment by rob006** [comment]
Did you tried to reset `yii\bootstrap4\Html::$counter`?

**Comment by tomlutzenberger** [comment]
No, only the currently tested class and `\yii\base\Widget`. I'll try this in the evening, thanks Rob.

**Comment by tomlutzenberger** [comment]
You were right, @rob006. I had to reset the HTML counter. The counters really need to get cleaned up. Very confusing.
I'll continue and submit a PR.
