### ISSUE TITLE
Travis HHVM fails because of PHPUnit

### ISSUE THREAD

**Issue by tomlutzenberger** [yiisoft/yii2-bootstrap4#68]
At this moment, all tests have been fixed and pass. Except HHVM.
The log (https://travis-ci.org/yiisoft/yii2-bootstrap4/jobs/432235776) says:
> Fatal error: Uncaught Error: array_creation_expression is not allowed in write context in /home/travis/build/yiisoft/yii2-bootstrap4/vendor/phpunit/phpunit/src/Framework/TestCase.php:1270

The line in question:
```php
    [$category, $locale] = $args;
```

Now I'm asking myself:
1. Is testing against HHVM necessary?
1. Is a failing HHVM run neglectable if all others pass?

**Comment by samdark** [comment]
1. For 2.0 yes.
2. Nope.

Try using `list()` explicitly.

**Comment by tomlutzenberger** [comment]
I can't because the line causing the error is **inside** PHPUnit.

**Comment by rob006** [comment]
@samdark Since this is a new package and there was never a HHVM support promise for it, wouldn't be more practical to not support HHVM at all? HHVM drops PHP support, most of PHP packages drops HHVM support (or never support it), why waste resources on HHVM if almost nobody will use it with PHP?

**Comment by samdark** [comment]
Makes sense actually. Let's drop it from travis.yml.

**Comment by tomlutzenberger** [comment]
Updated PR #67
