### ISSUE TITLE
using bootstrap4 cdn on yii2-advanced template?

### ISSUE THREAD

**Issue by CathChen003** [yiisoft/yii2-bootstrap4#83]
I'm trying to use Bootstrap4 through the official CDN.  I followed the steps as outlined in the [assets setup](https://github.com/yiisoft/yii2-bootstrap4/blob/master/docs/guide/assets-setup.md#using-cdn) but when I try to run the program I get an error that says "**Class yii\bootstrap4\BootstrapAsset does not exist**".  I would rather use the CDN than download a package; is it even possible?  I did so many web searches but I couldn't figure out how to get things to work.

I configured assetManager in `/frontend/config/main.php` as the guide told me to and copied the following into the `composer.json` file:
`"replace": {
    "bower-asset/bootstrap": ">=4.1.1"
},`

Can't figure out how to get it to work.  Any help would be appreciated, thanks!

| Q                | A
| ---------------- | ---
| Yii vesion       |  Latest stable release 2.*
| PHP version      |  7.*
| Operating system |  Windows

**Comment by simialbi** [comment]
Can you paste your config file please (be sure to anonymize any credentials like db pass)?

**Comment by CathChen003** [comment]
@simialbi 
> Can you paste your config file please (be sure to anonymize any credentials like db pass)?

Code is below.  Am I putting it into the wrong file?  It's in frontend/config/main.php

    <?php
    $params = array_merge(
        require __DIR__ . '/../../common/config/params.php',
        require __DIR__ . '/../../common/config/params-local.php',
        require __DIR__ . '/params.php',
        require __DIR__ . '/params-local.php'
    );
    
    return [
        'id' => 'app-frontend',
        'basePath' => dirname(__DIR__),
        'bootstrap' => ['log'],
        'controllerNamespace' => 'frontend\controllers',
        'components' => [
            'request' => [
                'csrfParam' => '_csrf-frontend',
            ],
            'user' => [
                'identityClass' => 'common\models\User',
                'enableAutoLogin' => true,
                'identityCookie' => ['name' => '_identity-frontend', 'httpOnly' => true],
            ],
            'session' => [
                // this is the name of the session cookie used for login on the frontend
                'name' => 'advanced-frontend',
            ],
            'log' => [
                'traceLevel' => YII_DEBUG ? 3 : 0,
                'targets' => [
                    [
                        'class' => 'yii\log\FileTarget',
                        'levels' => ['error', 'warning'],
                    ],
                ],
            ],
            'errorHandler' => [
                'errorAction' => 'site/error',
            ],
            'assetManager' => [
                // override bundles to use CDN :
                'bundles' => [
                    'yii\bootstrap4\BootstrapAsset' => [
                        'sourcePath' => null,
                        'baseUrl' => 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1',
                        'css' => [
                            'css/bootstrap.min.css'
                        ],
                    ],
                    'yii\bootstrap4\BootstrapPluginAsset' => [
                        'sourcePath' => null,
                        'baseUrl' => 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1',
                        'js' => [
                            'js/bootstrap.min.js'
                        ],
                    ],
                    'yii\bootstrap4\BootstrapThemeAsset' => [
                        'sourcePath' => null,
                        'baseUrl' => null,
                        'css' => []
                    ],
                ],
            ],
            /*
            'urlManager' => [
                'enablePrettyUrl' => true,
                'showScriptName' => false,
                'rules' => [
                ],
            ],
            */
        ],
        'params' => $params,
    ];`

**Comment by simialbi** [comment]
> Am I putting it into the wrong file?

No it looks ok. `BootstrapThemeAsset` [does not exists](https://github.com/yiisoft/yii2-bootstrap4/tree/master/src) any more. Remove it, otherwhise it will generate an error. It's still in the docs because yii2-bootstrap4 started as a fork from [yiisoft/yii2-bootstrap](https://github.com/yiisoft/yii2-bootstrap)

Can you remove it and try again and if it don't work paste your complete composer.json?

@samdark we have to update the docs here.

**Comment by CathChen003** [comment]
I tried it and it doesn't work; I'm getting the same error.  `composer.json` looks like this:
{
    "name": "Mine",
    "description": "My Project",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://localhost/frontend/web/index.php",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap4": "~1.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}

Right now I'm getting bootstrap 4 to work by including the .min.js and .min.css files in AppAsset.php and styling my pages regularly instead of using /yii2/bootstrap4/BoostrapAsset.

**Comment by simialbi** [comment]
And you were able to `composer install` respectively `composer update` with this config? Seems like you haven't done it yet, and that's why you get the errror above.

**Comment by CathChen003** [comment]
@simialbi  I didn't, but I just ran both `composer install` and `composer update` but got the result "Nothing to install or update".  Was I supposed to run it with `composer.phar` instead?

**Comment by simialbi** [comment]
no it's not relevant if you do via composer.phar or "installed" composer. Try the following:
Delete composer.lock file and rename vendor folder (e.g. to _bak_vendor) and do it again. Check the result if `yiisoft/yii2-bootstrap4` gets installed.
