### ISSUE TITLE
Update Version Lastet Bootstrap 4.1, Popper 1.14.13, Yii 2.015.

### ISSUE THREAD

**Issue by cjtterabyte** [yiisoft/yii2-bootstrap4#9]
Update Composer Lastet Version Packages Dependency,

**Comment by samdark** [comment]
@slinstj not at the moment :(

**Comment by Thoulah** [comment]
You can use the version of @simialbi for testing. Works like a charm! Add this to your composer.json:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/simialbi/yii2-bootstrap4"
        }
]
```

When his changes are merged at some point you can remove that repository and composer will be back using this official version.

**Comment by samdark** [comment]
@cjtterabyte would you please make a pull request out of the commit you've made?

**Comment by slinstj** [comment]
@Thoulah it seems good! Thank you. I've created a new Bs4Asset and I am using just that and pure html/css for now. But I will try that fork till here is ok.

**Comment by cjtterabyte** [comment]
Close Solved.
