### ISSUE TITLE
Migrating from yii2-bootstrap

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2-bootstrap4#93]
It would be nice to include a paragraph or more in the docs about what's required to upgrade from `yii2-bootstrap` to this extension.

Is there any changes that people would be confused about? Any quick adaptations that come to mind?

**Comment by samdark** [comment]
Would be a big thing.

**Comment by terabytesoftw** [comment]
I think it would be an excellent option to have a web with all the widgets in demo as it did @kartik-v  that allows the developer to explore all the components and change them live and see the result.

**Comment by looqmaan** [comment]
It would be nice to have a migration guide.
