### ISSUE TITLE
Removal of Progress::$barOptions

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2-bootstrap4#95]
With yii2-bootstrap, we were able to colorize a Progress bar like this:

```php
echo Progress::widget([
     'percent' => 65,
     'barOptions' => ['class' => 'progress-bar-danger']
]);
```
![screen shot 2019-01-16 at 12 36 06 am](https://user-images.githubusercontent.com/304450/51217010-be14da00-1926-11e9-8ff1-211b100ccbb9.png)

The adapted syntax for bootstrap4, with `barOptions` removed from the API looks like this:

```php
echo Progress::widget([
     'bars' => [
         [
             'percent' => 65,
             'options' => ['class' => 'progress-bar-danger']
         ]
     ],
]);
```

I feel like we've lost some syntactic sugar here. What was the reason for the removal  of `barOptions` ?

**Comment by machour** [comment]
As you can see from #97, as soon as I want anything more than the default blue bar, I need to set the `bars` property. Definitely looking like a drawback.

**Comment by samdark** [comment]
The reason for the change is https://getbootstrap.com/docs/4.0/components/progress/#multiple-bars

**Comment by machour** [comment]
Was already in bs3 & yii: https://github.com/yiisoft/yii2-bootstrap/blob/master/src/Progress.php#L45

**Comment by samdark** [comment]
Then I agree it's not convenient.
